<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup>
	<AnalysisMode>all</AnalysisMode>
	<EnableNETAnalyzers>true</EnableNETAnalyzers>
	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	<AnalysisLevel>6.0-all</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <None Remove="Helpers\**" />
    <Page Remove="Helpers\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="3d_models\Gib.stl" />
    <None Remove="3d_models\Karetka.stl" />
    <None Remove="3d_models\Konsol.stl" />
    <None Remove="3d_models\Prigim.stl" />
    <None Remove="3d_models\rolik inv.stl" />
    <None Remove="3d_models\rolik.stl" />
    <None Remove="3d_models\Zagim.stl" />
    <None Remove="appsettings.json" />
    <None Remove="appsettings.v2.json" />
    <None Remove="Resources\Fonts\ADLaMDisplay-Regular.ttf" />
    <None Remove="Resources\Icons\bending-roller-2.svg" />
    <None Remove="Resources\Icons\bending-roller.svg" />
    <None Remove="Resources\Icons\clamp-length-2.svg" />
    <None Remove="Resources\Icons\clamp-length.svg" />
    <None Remove="Resources\Icons\clamp-roller-inner-diameter.svg" />
    <None Remove="Resources\Icons\clamp-roller-outer-diameter.svg" />
    <None Remove="Resources\Icons\distance-from-clamp-roller-center-to-bend-axis-center.svg" />
    <None Remove="Resources\Icons\press-length-2.svg" />
    <None Remove="Resources\Icons\press-length.svg" />
    <None Remove="Resources\Icons\press-support.svg" />
    <None Remove="Resources\Icons\supply.svg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\ADLaMDisplay-Regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="3d_models\Gib.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="3d_models\Karetka.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="3d_models\Konsol.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="3d_models\Prigim.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="3d_models\rolik inv.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="3d_models\rolik.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="3d_models\Zagim.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="appsettings.v2.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\console.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\bending-roller-2.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\clamp-length-2.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\clamp-length.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\clamp-roller-inner-diameter.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\clamp-roller-outer-diameter.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\distance-from-clamp-roller-center-to-bend-axis-center.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\press-length-2.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\press-length.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\press-support.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Icons\supply.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Gcode.Utils" Version="0.2.21" />
    <PackageReference Include="HelixToolkit" Version="3.1.2" />
    <PackageReference Include="HelixToolkit.Core.Wpf" Version="2.27.3" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc5.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StarkCNC.Core\StarkCNC.Core.csproj" />
    <ProjectReference Include="..\StarkCNC.Database\StarkCNC.Database.csproj" />
    <ProjectReference Include="..\StarkCNC.Language\StarkCNC.Language.csproj" />
    <ProjectReference Include="..\StarkCNC.MachineCommunication\StarkCNC.MachineCommunication.csproj" />
    <ProjectReference Include="..\StarkCNC.Utilities\StarkCNC.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\BorderedLabeledTextBoxControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\ButtonWithIndicator.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FloorControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FlyoutMenuControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\LabeledTextBoxControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\PersonPicture.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Localization\Language.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Language.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Language.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Language.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Icons\bending-roller.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Project 11\source\repos\StarkCNC\StarkCNC\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Project 11\source\repos\StarkCNC\StarkCNC\.editorconfig" />
  </ItemGroup>

</Project>
