<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="General.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>General.resx</DependentUpon>
    </Compile>
    <Compile Update="SwitchToggle.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SwitchToggle.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="General.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>General.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="SwitchToggle.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SwitchToggle.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
